SELECT
    TO_CHAR(REFERENCIA, 'MM/YYYY') AS "Mes",
    HFU.CODEMP AS "ID Empresa",
    EMP.RAZAOSOCIAL AS "Empresa",
    DEP.CODDEP AS "ID Departamento",
    DEP.DESCRDEP AS "Departamento",
    CUS.CODCENCUS AS "ID Centro de Resultado",
    CUS.DESCRCENCUS AS "Centro de Resultado",
    CAR.CODCARGO AS "ID Cargo",
    CAR.DESCRCARGO AS "Cargo",
    FUN.CODFUNC AS "ID Colaborador",
    COUNT(DISTINCT HFU.CODFUNC) AS "Headcount",
    0 AS "Quantidade Admissões",
    0 AS "Quantidade Demissões"
FROM
    TFPHFU HFU
LEFT JOIN TSIEMP EMP ON EMP.CODEMP = HFU.CODEMP
LEFT JOIN TFPFCO FCO ON FCO.CODFUNCAO = HFU.CODFUNCAO
LEFT JOIN TFPCAR CAR ON HFU.CODCARGO = CAR.CODCARGO
LEFT JOIN TFPDEP DEP ON DEP.CODDEP = HFU.CODDEP
LEFT JOIN TSICUS CUS ON CUS.CODCENCUS = DEP.CODCENCUS  
LEFT JOIN TFPFUN FUN ON HFU.CODFUNC = FUN.CODFUNC   
WHERE HFU.SITUACAO <> 0


GROUP BY 
    TO_CHAR(REFERENCIA, 'MM/YYYY'),
    DEP.CODDEP,
    CAR.CODCARGO,
    FCO.CODFUNCAO,
    DEP.DESCRDEP,
    CUS.CODCENCUS,
    CUS.DESCRCENCUS,
    CAR.CODCARGO,
    CAR.DESCRCARGO,
    HFU.CODEMP,
    EMP.RAZAOSOCIAL,
    FUN.CODFUNC,
    FUN.NOMEFUNC

UNION ALL

SELECT
    TO_CHAR(DTADM, 'MM/YYYY') AS "Mes",
    EMP.CODEMP AS "ID Empresa",
    EMP.RAZAOSOCIAL AS "Empresa",
    DEP.CODDEP AS "ID Departamento",
    DEP.DESCRDEP AS "Departamento",
    CUS.CODCENCUS AS "ID Centro de Resultado",
    CUS.DESCRCENCUS AS "Centro de Resultado",
    CAR.CODCARGO AS "ID Cargo",
    CAR.DESCRCARGO AS "Cargo",
    FUN.CODFUNC AS "ID Colaborador",
    0 AS "Headcount",
    COUNT(DISTINCT CODFUNC) AS "Quantidade Admissões",
    0 AS "Quantidade Demissões"
FROM
        TFPFUN FUN
LEFT JOIN TFPFCO FCO ON FCO.CODFUNCAO = FUN.CODFUNCAO
LEFT JOIN TSIEMP EMP ON EMP.CODEMP = FUN.CODEMP
LEFT JOIN TFPCAR CAR ON FUN.CODCARGO = CAR.CODCARGO
LEFT JOIN TFPDEP DEP ON DEP.CODDEP = FUN.CODDEP
LEFT JOIN TSICUS CUS ON CUS.CODCENCUS = DEP.CODCENCUS 



GROUP BY
    TO_CHAR(DTADM, 'MM/YYYY'),
    DEP.CODDEP,
    CAR.CODCARGO,
    FCO.CODFUNCAO,
    DEP.DESCRDEP,
    CUS.CODCENCUS,
    CUS.DESCRCENCUS,
    CAR.CODCARGO,
    CAR.DESCRCARGO,
    EMP.CODEMP,
    EMP.RAZAOSOCIAL,
    FUN.CODFUNC,
    FUN.NOMEFUNC

UNION ALL

SELECT
    TO_CHAR(DTDEM, 'MM/YYYY') AS "Mes",
    EMP.CODEMP AS "ID Empresa",
    EMP.RAZAOSOCIAL AS "Empresa",
    DEP.CODDEP AS "ID Departamento",
    DEP.DESCRDEP AS "Departamento",
    CUS.CODCENCUS AS "ID Centro de Resultado",
    CUS.DESCRCENCUS AS "Centro de Resultado",
    CAR.CODCARGO AS "ID Cargo",
    CAR.DESCRCARGO AS "Cargo",
    FUN.CODFUNC AS "ID Colaborador",
    0 AS "Headcount",
    0 AS "Quantidade Admissões",
    COUNT(DISTINCT CODFUNC) AS "Quantidade Demissões"
FROM
        TFPFUN FUN
LEFT JOIN TFPFCO FCO ON FCO.CODFUNCAO = FUN.CODFUNCAO
LEFT JOIN TSIEMP EMP ON EMP.CODEMP = FUN.CODEMP
LEFT JOIN TFPCAR CAR ON FUN.CODCARGO = CAR.CODCARGO
LEFT JOIN TFPDEP DEP ON DEP.CODDEP = FUN.CODDEP
LEFT JOIN TSICUS CUS ON CUS.CODCENCUS = DEP.CODCENCUS 
WHERE DTDEM IS NOT NULL 
GROUP BY
    TO_CHAR(DTDEM, 'MM/YYYY'),
    DEP.CODDEP,
    CAR.CODCARGO,
    FCO.CODFUNCAO,
    DEP.DESCRDEP,
    CUS.CODCENCUS,
    CUS.DESCRCENCUS,
    CAR.CODCARGO,
    CAR.DESCRCARGO,
    EMP.CODEMP,
    EMP.RAZAOSOCIAL,
    FUN.CODFUNC,
    FUN.NOMEFUNC
   

     
