SELECT EVE.CODEVENTO AS "ID Evento",
       EVE.DESCREVENTO AS "Evento",
       GRU.CODEVENTO AS "ID Grupo Evento",
       GRU.DESCREVENTO AS "Grupo Evento"
FROM TFPEVE EVE
LEFT JOIN TFPEVE GRU ON GRU.CODEVENTO = EVE.GRUPOEVENTO
