SELECT
    TO_CHAR(FOL.REFERENCIA, 'MM/YYYY') AS MES,
    HFU.CODEMP AS ID_EMPRESA,
    EMP.RAZAOSOCIAL AS EMPRESA,
    DEP.CODDEP AS ID_DEPARTAMENTO,
    DEP.DESCRDEP AS DEPARTAMENTO,
    CUS.CODCENCUS AS ID_CENTRO_DE_RESULTADO,
    CUS.DESCRCENCUS AS CENTRO_DE_RESULTADO,
    CAR.CODCARGO AS ID_CARGO,
    CAR.DESCRCARGO AS CARGO,
    FOL.CODEVENTO AS ID_EVENTO,
    EVE.DESCREVENTO AS EVENTO,
    FUN.CODFUNC AS ID_COLABORADOR,
    SUM(FOL.VLREVENTO) AS FOLHA_DE_PAGAMENTO
    
FROM TFPFOL FOL
LEFT JOIN TFPHFU HFU ON HFU.CODFUNC = FOL.CODFUNC
AND HFU.REFERENCIA = FOL.REFERENCIA
LEFT JOIN TSIEMP EMP ON EMP.CODEMP = HFU.CODEMP
LEFT JOIN TFPFCO FCO ON FCO.CODFUNCAO = HFU.CODFUNCAO
LEFT JOIN TFPCAR CAR ON HFU.CODCARGO = CAR.CODCARGO
LEFT JOIN TFPDEP DEP ON DEP.CODDEP = HFU.CODDEP
LEFT JOIN TSICUS CUS ON CUS.CODCENCUS = DEP.CODCENCUS
LEFT JOIN TFPFUN FUN ON FUN.CODFUNC = FOL.CODFUNC
LEFT JOIN TFPEVE EVE ON EVE.CODEVENTO = FOL.CODEVENTO
LEFT JOIN (SELECT VALOR,OPCAO FROM TDDOPC WHERE NUCAMPO = 1847) SIT ON (SIT.VALOR = HFU.SITUACAO)
WHERE EVE.AD_GRUPEVE IS NOT NULL 
GROUP BY HFU.CODEMP,
         FCO.CODFUNCAO,
         EMP.RAZAOSOCIAL,
         FCO.DESCRFUNCAO,
         CAR.CODCARGO,
         CAR.DESCRCARGO,
         TO_CHAR(FOL.REFERENCIA, 'MM/YYYY'),
         DEP.CODDEP,
         DEP.DESCRDEP,
         CUS.CODCENCUS,
         CUS.DESCRCENCUS,
         EVE.DESCREVENTO,
         FOL.CODEVENTO,
         FUN.CODFUNC,
         FUN.NOMEFUNC
