SELECT
    FUN.CODFUNC AS "ID Colaborador",
    FUN.NOMEFUNC AS "Colaborador",
    EMP.CODEMP AS "ID Empresa",
    EMP.RAZAOSOCIAL AS "Empresa",
    DEP.CODDEP AS "ID Departamento",
    DEP.DESCRDEP AS "Departamento",
    CUS.CODCENCUS AS "ID Centro de Resultado",
    CUS.DESCRCENCUS AS "Centro de Resultado",
    CAR.CODCARGO AS "ID Cargo",
    CAR.DESCRCARGO AS "Cargo",
    FUN.NIVESC AS "ID Nível de Escolaridade",
    FUN.SEXO AS "ID Gênero",
    CASE WHEN FUN.SEXO = 'M' THEN 'Masculino' ELSE 'Feminino' END AS "Gênero",
    FUN.DTADM AS "Data de Admissão",
    FUN.DTDEM AS "Data de Demissão",
    FUN.SALBASE AS "Salário Base",
    YEAR(GETDATE()) - YEAR(FUN.DTNASC) AS "Idade",
    DATEDIFF(DAY, FUN.DTADM, GETDATE()) AS "Tempo de Casa",
    CASE 
        WHEN DATEDIFF(DAY, FUN.DTADM, GETDATE()) < 90 THEN 100
        WHEN DATEDIFF(DAY, FUN.DTADM, GETDATE()) BETWEEN 90 AND 180 THEN 200
        WHEN DATEDIFF(DAY, FUN.DTADM, GETDATE()) BETWEEN 181 AND 360 THEN 300
        WHEN DATEDIFF(DAY, FUN.DTADM, GETDATE()) BETWEEN 361 AND 540 THEN 400 
        WHEN DATEDIFF(DAY, FUN.DTADM, GETDATE()) BETWEEN 541 AND 720 THEN 500
        WHEN DATEDIFF(DAY, FUN.DTADM, GETDATE()) BETWEEN 721 AND 900 THEN 600
        WHEN DATEDIFF(DAY, FUN.DTADM, GETDATE()) BETWEEN 901 AND 1080 THEN 700
        WHEN DATEDIFF(DAY, FUN.DTADM, GETDATE()) BETWEEN 1081 AND 1440 THEN 800
        WHEN DATEDIFF(DAY, FUN.DTADM, GETDATE()) BETWEEN 1441 AND 1800 THEN 900
        ELSE 1000 
    END AS "ID Faixa tempo de Casa",
    CASE 
        WHEN DATEDIFF(DAY, FUN.DTADM, GETDATE()) < 90 THEN 'Período de Treinamento'
        WHEN DATEDIFF(DAY, FUN.DTADM, GETDATE()) BETWEEN 90 AND 180 THEN 'De 3 a 6 Meses'
        WHEN DATEDIFF(DAY, FUN.DTADM, GETDATE()) BETWEEN 181 AND 360 THEN 'De 6 a 12 Meses'
        WHEN DATEDIFF(DAY, FUN.DTADM, GETDATE()) BETWEEN 361 AND 540 THEN 'De 12 a 18 Meses' 
        WHEN DATEDIFF(DAY, FUN.DTADM, GETDATE()) BETWEEN 541 AND 720 THEN 'De 18 a 24 Meses' 
        WHEN DATEDIFF(DAY, FUN.DTADM, GETDATE()) BETWEEN 721 AND 900 THEN 'De 24 a 30 Meses' 
        WHEN DATEDIFF(DAY, FUN.DTADM, GETDATE()) BETWEEN 901 AND 1080 THEN 'De 30 a 36 Meses'
        WHEN DATEDIFF(DAY, FUN.DTADM, GETDATE()) BETWEEN 1081 AND 1440 THEN 'De 36 a 48 Meses'
        WHEN DATEDIFF(DAY, FUN.DTADM, GETDATE()) BETWEEN 1441 AND 1800 THEN 'De 48 a 60 Meses'
        ELSE 'Mais de 5 Anos' 
    END AS "Faixa tempo de Casa",
    CASE 
        WHEN FUN.SALBASE <= 2000 THEN 1
        WHEN FUN.SALBASE BETWEEN 2001 AND 4000 THEN 2
        WHEN FUN.SALBASE BETWEEN 4001 AND 6000 THEN 3       
        WHEN FUN.SALBASE BETWEEN 6001 AND 8000 THEN 4 
        ELSE 5 
    END AS "ID Faixa Salarial",
    CASE 
        WHEN FUN.SALBASE <= 2000 THEN 'Até R$ 2.000,00'
        WHEN FUN.SALBASE BETWEEN 2001 AND 4000 THEN 'Até R$ 4.000,00'
        WHEN FUN.SALBASE BETWEEN 4001 AND 6000 THEN 'Até R$ 6.000,00'       
        WHEN FUN.SALBASE BETWEEN 6001 AND 8000 THEN 'Até R$ 8.000,00' 
        ELSE 'Acima de R$ 8.000,00' 
    END AS "Faixa Salarial"
FROM
    TFPFUN FUN
LEFT JOIN TFPFCO FCO ON FCO.CODFUNCAO = FUN.CODFUNCAO
LEFT JOIN TSIEMP EMP ON EMP.CODEMP = FUN.CODEMP
LEFT JOIN TFPCAR CAR ON FUN.CODCARGO = CAR.CODCARGO
LEFT JOIN TFPDEP DEP ON DEP.CODDEP = FUN.CODDEP
LEFT JOIN TSICUS CUS ON CUS.CODCENCUS = DEP.CODCENCUS
LEFT JOIN (SELECT VALOR, OPCAO FROM TDDOPC WHERE NUCAMPO = 1826) ESC ON ESC.VALOR = FUN.NIVESC;
