SELECT FORMAT(DHBAIXA,'MM/yyyy') AS "Mes",
       EMP.CODEMP AS "ID Empresa",
       EMP.RAZAOSOCIAL AS "Empresa",
       VLRBAIXA AS "Faturamento"
FROM TGFFIN FIN
LEFT JOIN TSIEMP EMP ON FIN.CODEMP = EMP.CODEMP
WHERE DHBAIXA IS NOT NULL
  AND RECDESP =1
